#!/usr/bin/ash

reboot() { echo b > /proc/sysrq-trigger; }

cryptname="${1}"

# Abort if we do not know the cryptdevice
test -n "${cryptname}" || reboot

# Start udev from initramfs
/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never

# Suspend root device
cryptsetup luksSuspend "${cryptname}"

# Suspend the system
echo mem > /sys/power/state

# Resume root device
cryptsetup luksResume "${cryptname}" || reboot

# Stop udev from initramfs, as the real daemon from rootfs will be restarted
udevadm control --exit
